spring.application.name=SchoolManagementSystem



# JDBC Connection String
spring.datasource.url=jdbc:sqlserver://MututwaM-QS-SD\\\\LOCALDB#D612C41A;databaseName=sudodevelopmentdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=MUTUTWAM-QS-SD\mutut
spring.datasource.password=root
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver